spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rent
    username: rent
    password: rent
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

